name = "handles"
version = "3.1.0"

description = "Handles is a templating language written in pure Gleam. Heavily inspired by Mustache and Handlebars.js"
licences = ["MIT"]
repository = { type = "github", user = "olian04", repo = "gleam_handles" }
gleam = ">= 1.0.0"

[dependencies]
gleam_stdlib = ">= 0.38.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.1.2 and < 2.0.0"

[javascript]
# Generate TypeScript .d.ts files
typescript_declarations = true
