name = "handles"
version = "5.0.0"

description = "Handles is a templating language written in pure Gleam. Heavily inspired by Mustache and Handlebars.js"
licences = ["MIT"]

repository = { type = "github", user = "olian04", repo = "gleam_handles" }

gleam = ">= 1.4.0"

internal_modules = [
  "handles/internal",
  "handles/internal/*",
]

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
